[project]
name = "author-guessing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
